Completed and ready for review issue-3-user-can-edit-an-entry.
Mitchelllund/code-journal pull request #7
Opened 2022-07-25 23:05 UTC by Mitchelllund

![Code-Journal-#3](https://user-images.githubusercontent.com/90532731/180889151-c0b65008-5827-4569-8955-5a359ed0b02c.gif)

2022-07-25 23:14 UTC, Zhiwutian requested changes
Great work Mitch! Small update needed!

2022-07-25 23:14 UTC, Zhiwutian commented on js/main.js
> +    var entryLocation = $li.item(data.entries.length - data.editing.nextEntryId);
this is what you want to change. Once you start deleting entries, the numbers won't align in this way. Instead, you want to loop through all of the `li` elements and find the one with the matching entryid so you know which one to replace.

2022-07-27 02:19 UTC, Mitchelllund commented
![Code-Journal-#3 updates](https://user-images.githubusercontent.com/90532731/181146287-d8dfa833-a41e-436e-bed3-8ac4af24955b.gif)

2022-07-27 02:22 UTC, Zhiwutian approved these changes
👍🏼

2022-07-27 02:33 UTC, merged